#!/usr/bin/env bash

source "./_shared.sh"

# Recipe for installing a GNAT capable GCC cross-compiler.
# Assumes specific dirtree.
# ${HOME}/src/build
# source trees stored in 'src'

export BUILD_TARGET="i686-elf"
export BUILD_PREFIX="${HOME}/opt/cross"
export PATH="${BUILD_PREFIX}/bin:${PATH}"


echo "Building cross binutils for arch: '${BUILD_TARGET}'"
prompt_to_confirm

binutils_version="2.32"
binutils_dir="binutils-${binutils_version}"

if [[ ! -d "${binutils_dir}" ]]; then
	mkdir "${binutils_dir}" || exit 1
fi

cd "${binutils_dir}" || exit 1

../../${binutils_dir}/configure \
	--target=${BUILD_TARGET} \
	--prefix="${BUILD_PREFIX}" \
	--with-sysroot \
	--disable-nls \
	--disable-werror

make -j8 || die_with_error "Error building binutils"
make -j8  install || die_with_error "Error installing binutils"


echo "Building initial cross GCC build for arch: '${BUILD_TARGET}'"
prompt_to_confirm

gcc_version="8.3.0"
gcc_dir="gcc-${gcc_version}"

if [[ ! -d "${gcc_dir}" ]]; then
	mkdir "${gcc_dir}" || exit 1
fi

cd "${gcc_dir}" || exit 1

../../${gcc_dir}/configure \
	--target=${BUILD_TARGET} \
	--prefix="${BUILD_PREFIX}" \
	--enable-languages="c" \
	--with-newlib \
	--without-headers \
	--disable-shared \
	--disable-nls

make -j8 all-gcc || die_with_error "Error building initial GCC"
make -j8 install-gcc || die_with_error "Error installing initial GCC"


echo "Building newlib for arch: '${BUILD_TARGET}'"
prompt_to_confirm

newlib_version="3.1.0"
newlib_dir="newlib-${newlib_version}"

if [[ ! -d "${newlib_dir}" ]]; then
	mkdir "${newlib_dir}" || exit 1
fi

cd "${newlib_dir}" || exit 1

../../${newlib_dir}/configure \
	--target=${BUILD_TARGET} \
	--prefix="${BUILD_PREFIX}" \
	--disable-nls

make -j8 all || die_with_error "Error building newlib"
make -j8 install || die_with_error "Error installing newlib"


echo "Building GCC for arch: '${BUILD_TARGET}'"
prompt_to_confirm

cd "${gcc_dir}" || exit 1

../../${gcc_dir}/configure \
	--target=${BUILD_TARGET} \
	--prefix="${BUILD_PREFIX}" \
	--enable-languages="c,c++,ada" \
	--with-newlib \
	--disable-libada \
	--without-headers \
	--disable-shared \
	--disable-nls

make -j8 all-gcc || die_with_error "Error building GCC"
make -j8 install-gcc || die_with_error "Error installing GCC"
