#!/usr/bin/env sh

tag_name="${1}"
if [[ -z ${tag_name} ]]; then 
	echo "No tag name specified! Exiting."
	exit 1
fi

git tag --delete "${tag_name}"
git push --delete origin "${tag_name}"

git tag "${tag_name}"
git push origin "${tag_name}"
