#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;

# Creates a screenshot and saves it in the $HOME/Pictures directory.
#  Automatically copies the filename to the clipboard.


sub handle_error {
	my ($error_text) = @_;
	system "notify-send '$error_text'";
	die $error_text;
}


my $PICTURES_DIR="$ENV{HOME}/Pictures";
my $SCREENSHOT_UTILITY="/usr/bin/scrot";
my $CLIPBOARD_UTILITY="xclip -sel clip";


my $region = 0;
my $quality = 100;

GetOptions('quality=i' => \$quality,
	'region' => \$region);


my $timestamp = localtime(time);
$timestamp =~ s/\s/_/g;
my $screenshot_filename = "$PICTURES_DIR/screenshot_$timestamp.jpg";

my @screenshot_cmd = ($SCREENSHOT_UTILITY);
push @screenshot_cmd, "-q $quality";
push @screenshot_cmd, "-s" if $region;
push @screenshot_cmd, $screenshot_filename;


my $exit_status = system @screenshot_cmd;
handle_error "Unable to execute screenshot!" if $exit_status != 0;
system "notify-send 'Screenshot written to $screenshot_filename'";

open my $clipboard_stream, "|-", $CLIPBOARD_UTILITY
	or handle_error "Unable to open clipboard stream!";
print $clipboard_stream "$screenshot_filename"
