#!/usr/bin/env bash

source ./_shared.sh

# Script to setup git.


function print_usage {
  echo "Usage: $0 -e|--email 'git_email@here.com' - Script to set up git config." 1>&2
  exit 0
}


GIT_EMAIL=""

while [[ $# -gt 0 ]]; do
  key="${1}"

  case $key in
    -e|--email)
    GIT_EMAIL=${2}
    shift
    ;;
    -h|--help)
    print_usage
    exit 0
    shift
    ;;
    *)
    shift
    ;;
  esac
done


[[ -n "$GIT_EMAIL" ]] || die_with_message "No --email arg set! Exiting."

echo "Configuring git user for '${GIT_EMAIL}'"

# If not already present, generate RSA key.s
if [[ ! -f "${HOME}/.ssh/id_rsa" ]]; then
	ssh-keygen -t rsa -b 4096 -C "${GIT_EMAIL}"
fi

PROGRAMS=("git" "vim")
for PROGRAM in "${PROGRAMS[@]}"; do
	check_install_package "${PROGRAM}"
done

# Create symlink to the saved gitconfig.
config_dest="${HOME}/.gitconfig"
if [[ ! -f "${config_dest}" ]]; then 
  sudo ln -s "./.config/.gitconfig" ${config_dest}
fi

# Set up git identity
git config --global user.email "${GIT_EMAIL}"
git config --global user.name "Anthony"

echo "Finished setup!"
exit 0
